JNLP examples first version
leaningtech/labs.leaningtech.com pull request #28
Opened 2023-11-01 21:23 UTC by GabrielaReyna

Examples for application and applet

2023-11-01 21:29 UTC, GabrielaReyna commented
I think the links in the code blocks are being checked

2023-11-02 10:01 UTC, nanaian requested changes

2023-11-02 10:01 UTC, nanaian commented on src/content/docs/cheerpj3/13-examples/02-jnlp.mdx
> +You will download the applet JAR files by manually building the full URL and pasting it in the browser navigation bar. This is done by appending the `codebase` URL and the `jar` URL.
```suggestion
Download the applet JAR files by manually building the full URL and pasting it in the browser navigation bar. This is done by concatenating the `codebase` URL and the `jar` URL.
```

2023-11-02 10:01 UTC, nanaian commented on src/content/docs/cheerpj3/13-examples/02-jnlp.mdx
> +Create a directory where all the files will live. You can choose any name such `cheerpj-example-applet`:
```suggestion
Create a directory where all the files will live. You can choose any name, such as `cheerpj-example-applet`:
```

2023-11-02 10:01 UTC, nanaian commented
> I think the links in the code blocks are being checked

Modify the `exclude` regexes in `lychee.toml` to resolve this

2023-11-09 12:57 UTC, merged