server-client example tutorial
leaningtech/labs.leaningtech.com pull request #60
Opened 2024-01-17 16:53 UTC by GabrielaReyna

2024-01-18 15:51 UTC, GabrielaReyna commented
The lint warning is an example address in a code line. Is not a real link, should I add it to the list anyway?

2024-01-18 16:01 UTC, nanaian commented
> The lint warning is an example address in a code line. Is not a real link, should I add it to the list anyway?

Yes, we should ignore all loopback addresses. I think this isn't picked up because the port number is different

2024-01-26 16:16 UTC, nanaian requested changes

2024-01-26 16:16 UTC, nanaian commented on src/content/docs/cheerpj3/13-examples/04-serverclient.mdx
> +1. Open the `client.html`file and paste the following code:
```suggestion
1. Open the `client.html` file and paste the following code:
```

2024-01-26 16:16 UTC, nanaian commented on src/content/docs/cheerpj3/13-examples/04-serverclient.mdx
> +cd /ServerClientTutorial/Server/
Not sure about the absolute path here. Perhaps just remove the prefixing `/`?

2024-01-26 16:16 UTC, nanaian commented on src/content/docs/cheerpj3/13-examples/04-serverclient.mdx
> +cd /ServerClientTutorial/Client/
"

2024-01-30 09:13 UTC, merged